baseURL = "https://example.com/"
# 网站语言
languageCode = "zh"
# [en, zh, ...] 设定主题的国际化
defaultContentLanguage = "zh"
# 网站标题
title = "LoveIt 主题"
# 主题
theme = "LoveIt"
# 是否使用 git 信息来生成文章的上次修改时间
enableGitInfo = false
# 是否包括中日韩文字
hasCJKLanguage = true
# 默认每页列表显示的文章数目
paginate = 12
# 是否使用 emoji 代码
enableEmoji = true
# 是否使用 robots.txt
enableRobotsTXT = true
# [UA-XXXXXXXX-X] 谷歌分析代号
googleAnalytics = ""
# 版权描述，仅仅用于 SEO
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
# 日期格式
dateFormatToUse = "2006-01-02"

# Hugo 解析文档的配置
[markup]
  # 代码高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 作者信息
[author]
  name = "xxxx"
  link = ""

# 网站地图信息
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 信息 (https://gohugo.io/content-management/urls/#permalinks)
[Permalinks]
  posts = ":year/:month/:filename"

# 菜单信息
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "posts"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "categories"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "about"
    weight = 4

  [[menu.main]]
    identifier = "en"
    pre = '<i class="fas fa-language fa-fw"></i>'
    name = ""
    title = "English"
    url = "https://hugo-loveit-en.netlify.com"
    weight = 5

[params]
  # LoveIt 主题版本
  version = "0.1.X"
  # 网站描述
  description = "关于 LoveIt 主题"
  # 网站关键词
  keywords = ["Theme", "Hugo"]
  # 网站默认主题 ("light", "dark", "auto")
  defaultTheme = "auto"
  # 用于生成文章上次修改时间的公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""

  # 页面头部导航栏信息
  [params.header]
    # 桌面端导航栏模式 ("fixed", "normal", "auto")
    desktopMode = "fixed"
    # 移动端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"

  # 页面底部版权信息设置
  [params.footer]
    # 网站创立年份
    since = 2019
    # ICP 备案信息，仅在中国使用 (允许使用 HTML 格式)
    icp = ""
    # 许可协议信息 (允许使用 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # 主页信息设置
  [params.home]
    # 主页个人信息
    [params.home.profile]
      enable = true
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail = ""
      # 主页显示头像的 URL
      avatarURL = "images/avatar.png"
      # 主页显示的网站副标题
      subtitle = "一个简洁、优雅且高效的 Hugo 主题"
      # 是否为副标题显示打字机动画
      typeit = true
      # 是否显示社交账号
      social = true
    # 主页文章列表
    [params.home.posts]
      enable = true
      # 主页每页显示文章数量
      paginate = 6
      # 当你没有在文章前面设置 "hiddenFromHomePage" 时的默认行为
      defaultHiddenFromHomePage = false

  # 主页的社交信息设置
  [params.social]
    GitHub = "xxxx"
    # Linkedin = "xxxx"
    Twitter = "xxxx"
    Instagram = "xxxx"
    Email = "xxxx@outlook.com"
    # Facebook = "xxxx"
    # Telegram = "xxxx"
    # Medium = "xxxx"
    # Gitlab = "xxxx"
    # Youtubelegacy = "xxxx"
    # Youtubecustom = "xxxx"
    # Youtubechannel = "xxxx"
    # Tumblr ="xxxx"
    # Quora = "xxxx"
    # Keybase = "xxxx"
    # Pinterest = "xxxx"
    # Reddit = "xxxx"
    # Codepen = "xxxx"
    # FreeCodeCamp = "xxxx"
    # Bitbucket = "xxxx"
    # Stackoverflow = "xxxx"
    Weibo = "xxxx"
    # Odnoklassniki = "xxxx"
    # VK = "xxxx"
    # Flickr = "xxxx"
    # Xing = "xxxx"
    # Snapchat = "xxxx"
    # Soundcloud = "xxxx"
    # Spotify = "xxxx"
    # Bandcamp = "xxxx"
    # Paypal = "xxxx"
    # Fivehundredpx = "xxxx"
    # Mix = "xxxx"
    # Goodreads = "xxxx"
    # Lastfm = "xxxx"
    # Foursquare = "xxxx"
    # Hackernews = "xxxx"
    # Kickstarter = "xxxx"
    # Patreon = "xxxx"
    # Steam = "xxxx"
    # Twitch = "xxxx"
    # Strava = "xxxx"
    # Skype = "xxxx"
    # Whatsapp = "xxxx"
    Zhihu = "xxxx"
    Douban = "xxxx"
    # Angellist = "xxxx"
    # Slidershare = "xxxx"
    # Jsfiddle = "xxxx"
    # Deviantart = "xxxx"
    # Behance = "xxxx"
    # Dribble = "xxxx"
    # Wordpress = "xxxx"
    # Vine = "xxxx"
    # Googlescholar = "xxxx"
    # Researchgate = "xxxx"
    # Mastodon = "xxxx"
    # MastodonPrefix = "https://mastodon.technology/"
    # Thingiverse = "xxxx"
    # Devto = "xxxx"
    # Gitea = "xxxx"
    # XMPP = "xxxx"
    # Matrix = "xxxx"
    Bilibili = "xxxx"

  # 文章页面配置
  [params.page]
    # 在文章页面是否使用分享功能
    socialShare = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true

  # 文章页面的分享信息设置
  [params.share]
    enable = true
    Twitter = true
    Facebook = true
    # Linkedin = true
    # Whatsapp = true
    # Pinterest = true
    # Tumblr = true
    # HackerNews = true
    # Reddit = true
    # VK = true
    # Buffer = true
    # Xing = true
    # Line = true
    Instapaper = true
    Pocket = true
    # Digg = true
    # Stumbleupon = true
    # Flipboard = true
    Weibo = true
    Renren = true
    # Myspace = true
    # Blogger = true
    Baidu = true
    # Odnoklassniki = true
    Evernote = true
    # Skype = true
    # Trello = true
    # Mix = true

  # 数学公式 (KaTeX https://katex.org/)
  [params.math]
    enable = true
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    inlineLeftDelimiter = "$"
    inlineRightDelimiter = "$"
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX 插件 mhchem
    mhchem = true

  # CSS 和 JS 文件的 CDN 设置
  [params.cdn]
    ## 例如 '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    fontawesomeFreeCSS = ''
    animateCSS = ''
    gitalkCSS = ''
    gitalkJS = ''
    valineJS = ''
    lazysizesJS = ''
    smoothScrollJS = ''
    sharerJS = ''
    katexCSS = ''
    katexJS = ''
    katexAutoRenderJS = ''
    katexCopyTexCSS = ''
    katexCopyTexJS = ''
    katexMhchemJS = ''
    mermaidJS = ''
    echartsJS = ''
    echartsMacaronsJS = ''
    typeitJS = ''
    aplayerCSS = ''
    aplayerJS = ''
    metingJS = ''

  # 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  # 出版者信息，仅用于 SEO
  [params.publisher]
    name = "xxxx"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  # 网站图标信息，仅用于 SEO
  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  #  网站图标信息，仅用于 SEO
  [params.image]
    url = "cover.png"
    width = 800
    height = 600

  # 评论系统设置
  [params.comment]
    enable = true

    # Disqus 评论系统设置 (https://disqus.com/)
    [params.comment.disqus]
      # Disqus 的用户名，用来在文章中启用 Disqus 评论系统
      shortname = "dillonzq"

    # Gittalk 评论系统设置 (https://github.com/gitalk/gitalk)
    [params.comment.gitalk]
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""

    # Valine 评论系统设置 (https://github.com/xCss/Valine)
    [params.comment.valine]
      enable = false
      appId = ""
      appKey = ""
      placeholder = "你的评论 ..."
      notify = false
      verify = true
      avatar = "mp"
      # meta= ""
      pageSize = 10
      visitor = true
      recordIP = true

    # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
    [params.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = "en_US"

# 隐私信息设置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
